apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: alertmanager
    prometheus: app-sre
  name: rhobs-alertmanager
  namespace: openshift-customer-monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: web
  namespaceSelector:
    matchNames:
    - rhobs-stage
  selector:
    matchLabels:
      app.kubernetes.io/component: alertmanager
