apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: thanos-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: rhobs
    app.kubernetes.io/name: configmap
    app.kubernetes.io/part-of: thanos-operator
  name: thanos-operator-serving-cert
  namespace: rhobs-stage
