apiVersion: v1
data:
  rbac.yaml: |
    roleBindings:
    - name: 45b1e1f4-6e17-4858-8f66-158320f6ac71
      roles:
      - hcp-metrics-read
      - hcp-metrics-write
      - hcp-logs-read
      - hcp-logs-write
      - hcp-probes-read
      - hcp-probes-write
      subjects:
      - kind: user
        name: service-account-45b1e1f4-6e17-4858-8f66-158320f6ac71
    roles:
    - name: hcp-metrics-read
      permissions:
      - read
      resources:
      - metrics
      tenants:
      - hcp
    - name: hcp-metrics-write
      permissions:
      - write
      resources:
      - metrics
      tenants:
      - hcp
    - name: hcp-logs-read
      permissions:
      - read
      resources:
      - logs
      tenants:
      - hcp
    - name: hcp-logs-write
      permissions:
      - write
      resources:
      - logs
      tenants:
      - hcp
    - name: hcp-probes-read
      permissions:
      - read
      resources:
      - probes
      tenants:
      - hcp
    - name: hcp-probes-write
      permissions:
      - write
      resources:
      - probes
      tenants:
      - hcp
kind: ConfigMap
metadata:
  annotations:
    qontract.recycle: "true"
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/name: rhobs-gateway
    app.kubernetes.io/part-of: rhobs
    app.kubernetes.io/version: 1fb4dafb58f6158c832f307d8e37729f390f4f5a
  name: rhobs-gateway
  namespace: rhobs-stage
