apiVersion: monitoring.rhobs/v1
kind: Alertmanager
metadata:
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: rhobs
    app.kubernetes.io/managed-by: observability-operator
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: rhobs
  name: rhobs-alertmanager
  namespace: rhobs-stage
spec:
  alertmanagerConfigMatcherStrategy: {}
  replicas: 1
  resources: {}
status:
  availableReplicas: 0
  paused: false
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
